export enum JobSkill {
    Java = 'Java',
    SpringBoot = 'Spring Boot',
    Angular = 'Angular',
    React = 'React',
    NodeJs = 'Node.js',
    Python = 'Python',
    Django = 'Django',
    Flask = 'Flask',
    CSharp = 'C#',
    DotNet = '.NET',
    SQL = 'SQL',
    MongoDB = 'MongoDB',
    GraphQL = 'GraphQL',
    Docker = 'Docker',
    Kubernetes = 'Kubernetes',
    AWS = 'AWS',
    Azure = 'Azure',
    Firebase = 'Firebase',
    Flutter = 'Flutter',
    Swift = 'Swift',
  }
  