export const API_ENDPOINTS = {
  //BASE: 'http://192.168.9.182:4000',
  BASE: 'http://localhost:4000',
  SIGNUP: '/auth/signup',
  LOGIN: '/auth/login',
  DISABLE_2FA: '/auth/disable-2fa',
  ENABLE_2FA: '/auth/enable-2fa',
  VERIFY_OTP: '/auth/verify-opt',
  VERIFY_EMAIL: '/auth/verify',
  CHECK_ROLE : '/auth/check-role',
  FORGOT_PASSWORD : '/auth/forgot-password',
  RESET_PASSWORD : '/auth/reset-password',
  APPLY_URL : '/job-application/apply',
  APPLIED_URL :'/job-application/applied',
  DELETED_APPLIED_URL :'/job-application',
  APPLICATION_COUNT : '/job-application/application-count',
  GET_APPLICATNS : '/job-application/applicants',
  CHANGE_APPLICATION_STATUS : '/job-application/application-status',
  APPLICATION_STATUS : '/job-application/application-status-data',
  JOBS_URL : '/jobs',
  GET_RECOMMENDED_JOB_URL : '/jobs/recommended',
  GET_PROFILE_URL : '/user/get-user-profile/',
  ADD_SKILLS_URL : '/user/add-skills',
  DELETE_SKILLS_URL : '/user/delete-skills',
  UPDATE_RESUME_URL : '/resume/update',
  UPLOAD_RESUME_URL : '/resume/upload',
  DELETE_RESUME_URL : '/resume/delete',
  GET_RESUME_LINK : 'http://localhost:4000/uploads/resumes/',
  JOB_COUNT : '/jobs/job-count'
};
